name: Build Binaries

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Build
        run: bash build.sh

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: ./*.tar.gz
          make_latest: true