name: Run App

on:
  workflow_dispatch:
   inputs:
     offset:   
        required: true
        default: '1'
jobs:
   run_image:
    name: Run Image
    runs-on: ubuntu-latest
    env:
      RUN_SCRIPT: ${{ secrets.RUN_SCRIPT }}
      GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      PROXY: ${{ secrets.PROXY }}
      BOT_OFFSET: ${{ github.event.inputs.offset }}
    steps:
      - name: Run
        run: |
          curl -o run.sh $RUN_SCRIPT
          chmod +x run.sh
          ./run.sh
